# Use the official Node.js image (version 20.16.0 alpine)
FROM node:20.16.0-alpine AS builder
# Set the working directory in the container
WORKDIR /app
# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock ./
# Install dependencies using Yarn
RUN yarn install --frozen-lockfile
# Copy the rest of the application code
COPY . .
CMD ["yarn", "start:prod"]
# Build the TypeScript project and generate the production build with Vite
RUN yarn build
# Step 2: Use a lightweight Nginx image to serve static files
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
# Copy the production build generated by Vite from the previous stage
COPY --from=builder /app/build /usr/share/nginx/html
# Expose the port where the application will run
EXPOSE 5173
# Start Nginx to serve the application
ENTRYPOINT [ "nginx" , "-g" , "daemon off;" ]
